// @generated automatically by Diesel CLI.
// This is Schema is auto generated by the CLI command diesel migration run

diesel::table! {
    users (uuid) {
        uuid -> Int4,
        name -> Varchar,
        email -> Varchar,
        maried -> Nullable<Bool>,
        removed -> Bool,
        gender -> Text,
    }
}
